name: Android
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update || sudo apt-get update
        sudo apt-get install -y build-essential git
        sudo apt-get install -y openjdk-11-jdk-headless
        sudo apt-get install -y zlib1g-dev zip unzip pkg-config libffi-dev
        sudo apt-get install -y libltdl-dev
        sudo apt-get install -y lld
        pip install --upgrade buildozer
        pip install --upgrade Cython==0.29.19 virtualenv
        git clone -b python3.9 https://github.com/obfusk/kivy.git ../kivy
    - name: Build
      run: buildozer android debug
    - uses: actions/upload-artifact@v2
      with:
        name: APK
        path: |
          bin/*.apk
